# Generated by Django 2.0.7 on 2018-07-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postimg',
            field=models.URLField(default='no_data'),
        ),
    ]
