# Generated by Django 2.0.7 on 2018-07-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180719_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postcontent',
            field=models.CharField(max_length=1024),
        ),
    ]
