# Generated by Django 2.0.7 on 2018-07-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180719_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postboard',
            field=models.CharField(default='alt/random', max_length=32),
        ),
    ]
