# Generated by Django 2.0.7 on 2018-07-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180719_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardtopic', models.CharField(max_length=32)),
                ('boardposts', models.PositiveIntegerField()),
                ('boardname', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='postboard',
            field=models.CharField(default='r', max_length=32),
        ),
    ]
