# Generated by Django 2.0.7 on 2018-07-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180719_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postparent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
